/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        app: "#f5fbf8",
        brand: "#1f6f5b",
        "brand-soft": "#e7f3ef",
        ink: "#10231e",
        body: "#314d45",
        muted: "#557169",
        secondary: "#6f8580",
        disabled: "#9fb7af",
        held: "#9b5c18",
        error: "#9b1c1c",
        danger: "#8a1f1f",
        "danger-soft": "#f0dada",
        "warning-bg": "#fff8f2",
        "warning-border": "#f3cfb4",
        "warning-title": "#4a2013",
        "warning-text": "#7f5542",
        "sold-out-bg": "#f4e1d6",
        "sold-out-border": "#ead4d4",
        "sold-out-surface": "#fff7f7",
        "sold-out-text": "#7f3f24",
        "success-border": "#bdd8ce",
        "success-soft": "#dff6ed",
        "success-strong": "#155443",
        "border-muted": "#a8c7bd",
        "border-subtle": "#d7e4df",
        "timer-border": "#cce0d9",
      },
    },
  },
  plugins: [],
};
